# # #

name: cmet-accounts

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  accounts-db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./accounts.dump:/dump/db.dump
      - ./local-setup.sh:/docker-entrypoint-initdb.d/init.sh
      - ./local-keyfile.key:/data/replica.key
    entrypoint:
      - bash
      - -c
      - |
          chmod 400 /data/replica.key
          chown 999:999 /data/replica.key
          exec docker-entrypoint.sh $$@
    command: mongod --bind_ip_all --auth --replSet rs0 --keyFile /data/replica.key --port 27017
