# # #
name: tml-accounts

volumes:
    mongo:

networks:
    common:

# # #

services:

    # # # # # # # # # # # # # # # # # # # # #
    # # # # # # # # # # # # # # # # # # # # #
    
    accounts:
        image: ghcr.io/carrismetropolitana/accounts-server:main
        restart: always
        ports:
            - 5050:5050
        networks:
            - common
        env_file:
            - ./.env.production
        depends_on:
            mongo:
                condition: service_healthy
                restart: true

    # # # # # # # # # # # # # # # # # # # # #
    # # # # # # # # # # # # # # # # # # # # #

    certbot:
        image: certbot/certbot
        deploy:
            restart_policy:
                condition: on-failure
                delay: 30s
            resources:
                limits:
                    memory: 100mb
        logging:
            options:
                max-size: '1m'
                max-file: '1'
        volumes:
        - ./letsencrypt:/etc/letsencrypt
        - certbotdata:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    # # # # # # # # # # # # # # # # # # # # #
    # # # # # # # # # # # # # # # # # # # # #

    mongo:
        image: mongo:latest
        container_name: mongo
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db
        networks:
            - common
        env_file:
            - ./.env.production
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh
            interval: 10s
            timeout: 5s
            retries: 5

    # # # # # # # # # # # # # # # # # # # # #
    # # # # # # # # # # # # # # # # # # # # #

    nginx:
        image: nginx:alpine-slim
        deploy:
            restart_policy:
                condition: on-failure
                delay: 30s
            resources:
                limits:
                    memory: 1gb
        logging:
            options:
                max-size: '1m'
                max-file: '1'
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/uptime.conf:/etc/nginx/conf.d/uptime.conf:ro
        - ./letsencrypt:/etc/letsencrypt:ro
        - certbotdata:/var/www/certbot:ro
        ports:
        - 80:80
        - 443:443
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''