name: 'CMET Accounts | Build & Push'

on:
  workflow_dispatch:
  push:
    branches:
      - production
      - staging

# # #

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  server:
    name: Server (NodeJS)
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./apps/server
          file: ./apps/server/Dockerfile
          tags: ghcr.io/carrismetropolitana/accounts-server:${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # #

  nginx:
    name: nginx
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./apps/nginx
          file: ./apps/nginx/Dockerfile
          tags: ghcr.io/carrismetropolitana/accounts-nginx:${{ github.ref_name }}
          build-args: NGINX_SERVER_NAME=${{ github.ref_name == 'staging' && 'staging.accounts.carrismetropolitana.pt' || 'accounts.carrismetropolitana.pt' }}


  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  filter-service:
    name: Filter Service (Go)
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./apps/filter-service
          file: ./apps/filter-service/Dockerfile
          tags: ghcr.io/carrismetropolitana/accounts-filter-service:${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  notifications-service:
    name: Notifications Service (Go)
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./apps/notifications-service
          file: ./apps/notifications-service/Dockerfile
          tags: ghcr.io/carrismetropolitana/accounts-notifications-service:${{ github.ref_name }}